export const FETCHING_HOLIDAYS_DATA = 'FETCHING_HOLIDAYS_DATA';
export const FETCHING_HOLIDAYS_SUCCESS = 'FETCHING_HOLIDAYS_SUCCESS';
export const FETCHING_HOLIDAYS_FAILURE = 'FETCHING_HOLIDAYS_FAILURE';
